import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

export default function Login() {
  const { login, register } = useAuth(); const navigate = useNavigate();
  const [portal, setPortal] = useState("citizen"), [mode, setMode] = useState("login");
  const [form, setForm] = useState({name:"",email:"",password:"",locality:""}), [error,setError]=useState(""), [submitting,setSubmitting]=useState(false);
  const update=k=>e=>setForm(f=>({...f,[k]:e.target.value}));
  const submit=async e=>{e.preventDefault();setError("");setSubmitting(true);try{const user=mode==="login"?await login(form.email,form.password,portal):await register(form);navigate(["authority","admin"].includes(user.role)?"/admin":"/dashboard")}catch(err){setError(err.response?.data?.message||"Could not sign in. Please check your details.")}finally{setSubmitting(false)}};
  return <main className="login-page"><section className="login-card"><div className="eyebrow">STRIX secure access</div><h1>{portal === "admin" ? "Municipal Admin Portal" : "Welcome to Strix"}</h1><p className="page-subtitle">{portal === "admin" ? "Sign in with your issued authority account to manage civic operations." : "Sign in to save reports and track civic updates across devices."}</p><div className="portal-switch"><button type="button" className={portal==="citizen"?"selected":""} onClick={()=>{setPortal("citizen");setMode("login")}}>Citizen</button><button type="button" className={portal==="admin"?"selected":""} onClick={()=>{setPortal("admin");setMode("login")}}>Admin / Authority</button></div>{portal==="citizen"&&<div className="mode-switch"><button type="button" className={mode==="login"?"selected":""} onClick={()=>setMode("login")}>Sign in</button><button type="button" className={mode==="register"?"selected":""} onClick={()=>setMode("register")}>Create citizen account</button></div>}<form onSubmit={submit}>{mode==="register"&&<><div className="field"><label>Name</label><input required value={form.name} onChange={update("name")} placeholder="Your name"/></div><div className="field"><label>Locality</label><input value={form.locality} onChange={update("locality")} placeholder="Your ward or locality"/></div></>}<div className="field"><label>Email address</label><input required type="email" value={form.email} onChange={update("email")} placeholder="you@example.com"/></div><div className="field"><label>Password</label><input required type="password" value={form.password} onChange={update("password")} placeholder="••••••••"/></div>{error&&<div className="report-alert report-alert-error">{error}</div>}<button className="dark-btn login-submit" disabled={submitting}>{submitting?"Please wait…":portal==="admin"?"Sign in to admin panel":mode==="register"?"Create account":"Sign in"}</button></form></section></main>;
}
